# backend/utils/logging/error_categories.py

class ErrorCategory:
    OCR_HEADER = "OCR_HEADER"
    OCR_TABLE = "OCR_TABLE"
    OCR_REDACTION = "OCR_REDACTION"

    LLM_EXTRACTION = "LLM_EXTRACTION"
    LLM_CLASSIFICATION = "LLM_CLASSIFICATION"

    DATA_VALIDATION = "DATA_VALIDATION"
    FILE_IO = "FILE_IO"

    DB_INSERT = "DB_INSERT"
    DB_CONNECTION = "DB_CONNECTION"

    PIPELINE_FAILURE = "PIPELINE_FAILURE"
    UNKNOWN = "UNKNOWN"
