GSK_PRODUCTS_LIST = [
    # Original Items
    "AUGMENTIN DDS 30ML SUSP",
    "BETNESOL FORTE 1MG TAB",
    "VELOZ L CAP",
    "AUGMENTIN DUO 625MG TAB",
    "BETNOVATE N CREAM 25GM",
    "BETNESOL FORTE 1MG TAB (1X20)",
    "VELOZ L CAP (1X10)",
    "AUGMENTIN DUO 625MG TAB 10S (AMOXICILLIN+POT.CLAV ULANATE) GSK",
    "BETNOVATE N CREAM 25GM GSK",
    "CEFTUM (CEFUROXIME) 500 MG TAB 1x4 GSK",
    "AUGMENTIN 625MG TAB (1X10)",
    "AUGMENTIN DUO 1GM TAB (1X10)",
    " 10GM OINT",
    "ZENTEL 400MG TAB (1X1)",

    # New Items From Material Description Table
    "AUGMENTIN DDS WFR 400MG/57MG/5ML 1X30ML",
    "AUGMENTIN ES SUSP 642.9MG/5ML 50ML_IN",
    "AUGMENTIN DUO 1X30ML",
    "AUGMENTIN I.V. 1.2G X1",
    "AUGMENTIN I.V. 300MG X1",
    "AUGMENTIN I.V. 600MG X1",
    "AUGMENTIN 1G DUO TABLET 5X10",
    "AUGMENTIN 375 TABLET 5X10",
    "AUGMENTIN 625 DUO TABLET 10X10",

    "AVAMYS NASAL SPRAY 0.05% 1X120D_IN-GSK",
    "BANOCIDE FORTE TAB 100MG 20X30",
    "BANOCIDE TAB 50MG 20X20",
    "BECADEXAMIN CAPSULE 1X60",
    "BETNESOL FORTE TABLETS 25X20",
    "BETNESOL N EYE/EAR DROPS X5ML",
    "BETNESOL ORAL DROPS 0.5MG X15M",
    "BETNESOL TABLET 0.5MG 1X20_(72) (18x4 )",
    "BETNOVATE C SKIN CREAM 30 GM TP",
    "BETNOVATE GM SKIN CREAM 20G_TP-LAM",
    "BETNOVATE N SKIN CREAM 25G_TP- LAMI",
    "BETNOVATE S SKIN OINT 20G",
    "BETNOVATE SKIN CREAM 20G TP-LAMI",

    "CALPOL PAEDIATRIC DROPS X15ML",
    "CALPOL SUSPENSION 120MG X60 ML",
    "CALPOL SUSPENSION 250MG X60 ML",
    "CALPOL T TABLETS TABLET 325/37.5MG 5X15",
    "CALPOL 500 MG + TABLET 45X15",
    "CALPOL 650 MG + TABLET 10X3X15",
    "CALPOL TABLET 500MG + 1X1000",

    "CCM TABLETS 250MG/100IU/50MCG 6X40",

    "CEFTUM TAB 125MG 5X4",
    "CEFTUM TABLET 250MG 5X4",
    "CEFTUM TABLET 500MG 5X10",

    "COBADEX CZS TABLET 20X15",
    "DAPSONE TAB 100MG X1000",
    "DERMOCALM LOTION X100ML",

    "ELTROXIN 125MCG TABS 20X60_CRSF",
    "ELTROXIN TABLET 25MCG 20X120_CRSF",
    "ELTROXIN 88MCG TABS 20X60_CRSF",
    "ELTROXIN TABLET 100MCG 1X120_CRSF",
    "ELTROXIN TABLET 50MCG 20X120_CRSF",
    "ELTROXIN TAB 75MCG 20X120_CRSF",
    "ELTROXIN TABLET 37.5MCG 20X120S_CRSF_TP",
    "ELTROXIN TABLET 12.5MCG 20X120S_CRSF_TP",

    "EUMOSONE M SKIN CREAM X15G",
    "EUMOSONE SKIN CREAM 1X15G",

    "FEFOL Z CAPS X15",

    "FLIXONASE ANS 50MCG 1X120D_PLT IN",
    "FLUTICBACT OINTMENT 1X10G",
    "FLUTIVATE CREAM 20G_TP",
    "FLUTIVATE E CREAM X30G",
    "FLUTIVATE OINTMENT 0.005 %W/W 1X20G",

    "LANOXIN TABLET 250MCG 25X10",

    "NEOSPORIN ANTIBIOTIC OINTMENT 1X10G",
    "NEOSPORIN H EAR DROPS X5ML",
    "NEOSPORIN POWDER X10G",
    "NEOSPORIN SKIN OINTMENT 30G",
    "NEOSPORIN-H OINTMENT X5G",

    "NUCALA FD 100MG 1X10ML",
    "NUCALA SOLUTION AI 100MG/ML1X1ML_IN-GSK",

    "OILATUM BAR 100G",
    "OILATUM CREAM 40GM",
    "OILATUM EMOLLIENT 100ML",
    "OILATUM KIDS BAR 50G",
    "OILATUM LOTION 100ML",

    "PHEXIN BD TABS 375MG 10X10",
    "PHEXIN BD TABS 750MG 10X10",
    "PHEXIN CAPS 250MG 10X10",
    "PHEXIN CAPS. 500 MG 10X10",
    "PHEXIN DISP TAB 250MG 10X10",
    "PHEXIN KID TABS 10X10",
    "PHEXIN ORAL SOLUTION 100MG/ML 10MLX1",
    "PHEXIN REDISYP SUSP 125MG X60ML",
    "PHEXIN REDISYP SUSP 250MG X60ML",
    "PHEXIN SUSPENSION 30 ML",

    "PHYSIOGEL HYPOALLERGENIC CRAI CRM 1X50G",
    "PHYSIOGEL HYPOALLERGENIC CRAI LOTN 100ML",
    "PHYSIOGEL A.I. BODY LOTION 1X400ML",
    "PHYSIOGEL HYPOALLERGENIC DMT CREAM 1X75G",
    "PHYSIOGEL HYPOALLERGENIC DMT LOTN 100ML",
    "PHYSIOGEL CLEANSER 1X150ML",

    "PIRITON CS COUGH SUPPRES X100ML",
    "PIRITON EXPECTORANT X100ML",
    "PIRITON EXPECTORANT X460ML",

    "SERETIDE DISKUS 50/250MCG 1X60D_IN/T",
    "SERETIDE DISKUS 50/500MCG 1X60D IN/T",

    "SUPACEF 1,5G/26ML TP X1 IN",
    "SUPACEF 250MG/17 ML TP X5",
    "SUPACEF 750MG/17ML TP X1 IN",

    "T-BACT CREAM 1X10G_TP",
    "T-BACT OINTMENT 5G_TP_LAMI",
    "T-BACT OINTMENT 15G_TP_LAMI",

    "TENOVATE GN SKIN CRM 20G TP",
    "TENOVATE M SKIN CREAM X15G",
    "TENOVATE OINTMENT X15G",
    "TENOVATE SKIN CREAM X30G",

    "TRELEGY ELLIPTA 100/62.5/25MCG 1X30D_IN",

    "ZENTEL SUSPENSION X10ML",
    "ZENTEL TABLET 400MG 10X10",

    "ZIMIVIR TAB 1000MG 7X3",
    "ZIMIVIR TAB 500MG 7X3",

    "ZODERM E CREAM 1% X50G",

    "ZOVIRAX SUSPENSION X100ML",
    "ZOVIRAX TABLETS 200MG 5X5'S",
    "ZOVIRAX TABLETS 400MG 5X10'S",
    "ZOVIRAX TABLETS 800MG 5X5",

    "ZYLORIC TABLET 100MG 25X10",
    "ZYLORIC TABLET 300MG 25X10",

    "ZEJULA TABLET 100MG 8X7",

    "JEMPERLI VIAL 50MG/ML 1X10ML_IN-GSK",

    "BOOSTRIX SLCF 48M IN",
    "FLUARIX TETRA QIV SLCF IN NH",
    "HAVRIX 720 Vial X 10 CT IN",
    "INFANRIX HEXA (HB-IPV SLCF +HIB) 48M IN",
    "MENVEO VIAL +VIAL 48M IN",
    "PRIORIX VIAL+DIL.PRTC IN",
    "ROTARIX LIQUID PFS IN",
    "SHINGRIX VIAL + AS01B VIAL IN",
    "SYNFLORIX SLCF IN",
    "VARILRIX.VIAL WHSA +DIL.PRTC IN",
]

# ---------------------------------------------------------------
# BRAND LIST (Unique brand names only)
# ---------------------------------------------------------------
GSK_BRANDS = {
    "AUGMENTIN", "AVAMYS", "BANOCIDE", "BECADEXAMIN", "BETNESOL", "BETNOVATE",
    "CALPOL", "CCM", "CEFTUM", "COBADEX", "DAPSONE", "DERMOCALM", "ELTROXIN",
    "EUMOSONE", "FEFOL", "FLIXONASE", "FLUTIBACT", "FLUTIVATE", "LANOXIN",
    "NEOSPORIN", "NEOSPORIN-H", "NUCALA", "OILATUM", "PHEXIN", "PHYSIOGEL",
    "PIRITON", "SERETIDE", "SUPACEF", "T-BACT", "TBACT", "T BACT","TENOVATE","EUMOSONE-M" ,"TRELEGY",
    "ZENTEL", "ZIMIVIR", "ZODERM", "ZOVIRAX", "ZYLORIC", "ZEJULA",
    "JEMPERLI", "BOOSTRIX", "FLUARIX", "HAVRIX", "INFANRIX", "MENVEO",
    "PRIORIX", "ROTARIX", "SHINGRIX", "SYNFLORIX", "VARILRIX", "VELOZ"
}

 
#GMM Code to call LLM to identify valid item rows