GSK_PRODUCTS_LIST = [
    "AUGMENTIN DDS 30ML SUSP",
    "BETNESOL FORTE 1MG TAB",
    "VELOZ L CAP",
    "AUGMENTIN DUO 625MG TAB",
    "BETNOVATE N CREAM 25GM",
    "BETNESOL FORTE 1MG TAB (1X20)",
    "VELOZ L CAP (1X10)",
    "AUGMENTIN DUO 625MG TAB 10S (AMOXICILLIN+POT.CLAV ULANATE) GSK",
    "BETNOVATE N CREAM 25GM GSK",
    "CEFTUM (CEFUROXIME) 500 MG TAB 1x4 GSK",
    "AUGMENTIN 625MG TAB (1X10)",
    "AUGMENTIN DDS 30ML SUSP",
    "AUGMENTIN DUO 1GM TAB (1X10)",
    "FLUTIBACT 10GM OINT",
    "ZENTEL 400MG TAB (1X1)",
    "NOSKURF 150ML LOTN"
]